app: s3memestorage
service: S3MemeStorage

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  environment:
    S3_BUCKET: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}"

functions:
  MemeGenerator:
    handler: meme_generator.handler
    runtime: python3.11
    events:
      - http:
          path: upload
          method: post
          request:
            schemas:
              application/json:
                schema:
                  type: object
                  properties:
                    image:
                      type: string
                      description: "Base64 encoded image"
                    text-top:
                      type: string
                      description: "Additional text data"
                    text-bottom:
                      type: string
                      description: "Additional text data"
                  required:
                    - image
                    - text-top
                    - text-bottom
plugins:
  - serverless-offline
  - serverless-s3-local

custom:
  s3:
    host: localhost
    port: 4569
    directory: .s3
    accessKeyId: S3RVER
    secretAccessKey: S3RVER
    bucketName: ${self:provider.environment.S3_BUCKET}

resources:
  Resources:
    UrlStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}

